name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: MySql in GitHub Actions
      # You may pin to the exact commit or the version.
      # uses: nnhy/mysql-action@222a90440dbe61dc5b4d971ef8117eaf3858e24b
      uses: nnhy/mysql-action@v1.0
      
      
    - name: Run Tests
      run: composer test
